config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  root 'public_recipes#index'
  get 'general_shopping_list/index'
  resources :recipe_foods
  devise_for :user
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :recipes
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  get 'shopping_list' => 'foods#shopping_list'
  # resources :food_recipes
  # Defines the root path route ("/")
  # root "articles#index"
  # resources :users, only: [:index, :show] do
  # end
  # root "pages#home"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    cannot :read, :all
    return unless user.present?

    can :create, :all
    can :destroy, :all, user_id:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods
  validates :food, :measurement_unit, :price, :quantity, presence: true
  validates :price, numericality: { greater_than: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  belongs_to :user, foreign_key: 'user_id'
  has_many :recipe_foods, foreign_key: 'recipe_id', dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :preparation_time, presence: true, comparison: { greater_than: 0 }
  validates :cooking_time, presence: true, comparison: { greater_than: 0 }
  validates :description, presence: true, length: { minimum: 3, maximum: 300 }
  validates :public, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, foreign_key: 'food_id'
  belongs_to :recipe, foreign_key: 'recipe_id'

  validates :quantity, comparison: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes, foreign_key: :user_id, dependent: :destroy
  has_many :foods, foreign_key: :user_id, dependent: :destroy
  validates :name, :email, presence: true

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email password password_confirmation current_password])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  def index
    @foods = Food.all
  end

  def new; end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    if @food.save
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.destroy
      redirect_to foods_path, notice: 'Food was successfully deleted.'
    else
      render :new, notice: 'Food was not deleted.'
    end
  end

  def shopping_list
    food_list = Food.all
    recipe_foods = RecipeFood.all

    @shopping_list = []
    food_list.each do |food|
      recipe_foods.each do |recipe_food|
        next unless food.quantity < recipe_food.quantity && food.id == recipe_food.food_id

        recipe_food.quantity -= food.quantity
        @shopping_list << food
        price = food.price * food.quantity
        @total_price = @total_price.to_i + price.to_i
      end
    end
  end

  private

  def food_params
    params.permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @public_recipes = Recipe.where(public: true)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!

  def new
    @recipes = Recipe.all
  end

  def create
    @recipes = Recipe.all
    @recipe_food = RecipeFood.new(recipe_food_params)

    if @recipe_food.save
      redirect_to root_path, notice: 'Recipe food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def recipe_food_params
    params.permit(:recipe_id, :food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @current_user = current_user
    @recipes = @current_user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    user = current_user
    @recipe = user.recipes.find(params[:id])
    @foods = RecipeFood.where(recipe_id: @recipe.id).includes(:food)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_url, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        flash[:error] = 'Error: recipe could not be saved'
        redirect_to new_recipe_url
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    render :edit, status: :unprocessable_entity unless @recipe.update(public: !@recipe.public)
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :description, :prepration_time, :cooking_time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/general_shopping_list_helper.rb
module GeneralShoppingListHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Recipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>

  <header>
  <%= render "shared/navbar" %>
  </header>
   <% if notice %>
 <p class="alert alert-success"><%= notice %></p>
<% end %>
 <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
 <% end %>
   </body>
   <%= yield %>
 </html>

app/views/pages/home.html.erb
<% if @public_recipes && @public_recipes.empty?%>
    <div>
        <p>No public recipes</p>
    </div>
<%else%>
<div>
<%@public_recipes.each do |public_recipe| %>
    <% sum = 0 %>
    <%= link_to recipe_path(public_recipe.id) do %>
        <div>
        <div>
            <p><%= public_recipe.name%></p>
            <p><%= "By: " + public_recipe.user.name %></p>
            </div>
            <div>
            <p><%= "Total food item: #{public_recipe.food_items.count}" %></p>
            <% public_recipe.recipe_foods.each {|recipe_food| sum += recipe_food.quantity * recipe_food.food.price} %>
            <p><%= "Total value: #{sum}" %></p>
            </div>
        </div>
    <% end %>
<%end%>
</div>
<%end%>

app/views/shared/_navbar.html.erb
    
    <nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
      <a href="#" class="font-semibold text-xl tracking-tight"><%=link_to "My Recipe", root_path%></a>
    </div>

    
    <div class="block lg:hidden">
      <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>
    </div>
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
      <div class="text-sm lg:flex-grow">
      <% if current_user %>
        <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
          Home
        </a>
        <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
        <%= link_to "Foods", foods_path %>
        </a>
        <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
          <%= link_to "Recipes", recipes_path %>
        </a>
        <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
          <%= link_to "Shopping List", general_shopping_list_index_path %>
        </a>
      </div>
        </div>
    <div class="flex items-center flex-shrink-0 text-white">
      <a href="#" class="font-semibold text-xl tracking-tight"><%=button_to "Logout", destroy_user_session_path, method: :delete %></a>
    </div>
    <% end %>
    <% if !current_user %>
    <div class="flex justify-end text-white gap-3">
      <a href="#" class="font-semibold text-xl tracking-tight"><%=link_to "Login", new_user_session_path %></a>
      <a href="#" class="font-semibold text-xl tracking-tight text-end"><%= link_to "Sign up", new_user_registration_path %></a>
    </div>
    <% end %> 
  </nav>