config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  root 'public_recipes#index'
  get 'general_shopping_list/index'
  resources :recipe_foods
  devise_for :user
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :recipes
  resources :foods, only: [:index, :show, :new, :create, :destroy]
  get 'shopping_list' => 'foods#shopping_list'
  # resources :food_recipes
  # Defines the root path route ("/")
  # root "articles#index"
  # resources :users, only: [:index, :show] do
  # end
  # root "pages#home"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    cannot :read, :all
    return unless user.present?

    can :create, :all
    can :destroy, :all, user_id:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods
  validates :food, :measurement_unit, :price, :quantity, presence: true
  validates :price, numericality: { greater_than: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  belongs_to :user, foreign_key: 'user_id'
  has_many :recipe_foods, foreign_key: 'recipe_id', dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :preparation_time, presence: true, comparison: { greater_than: 0 }
  validates :cooking_time, presence: true, comparison: { greater_than: 0 }
  validates :description, presence: true, length: { minimum: 3, maximum: 300 }
  validates :public, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, foreign_key: 'food_id'
  belongs_to :recipe, foreign_key: 'recipe_id'

  validates :quantity, comparison: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes, foreign_key: :user_id, dependent: :destroy
  has_many :foods, foreign_key: :user_id, dependent: :destroy
  validates :name, :email, presence: true

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email password password_confirmation current_password])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  def index
    @foods = Food.all
  end

  def new; end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    if @food.save
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.destroy
      redirect_to foods_path, notice: 'Food was successfully deleted.'
    else
      render :new, notice: 'Food was not deleted.'
    end
  end

  def shopping_list
    food_list = Food.all
    recipe_foods = RecipeFood.all

    @shopping_list = []
    food_list.each do |food|
      recipe_foods.each do |recipe_food|
        next unless food.quantity < recipe_food.quantity && food.id == recipe_food.food_id

        recipe_food.quantity -= food.quantity
        @shopping_list << food
        price = food.price * food.quantity
        @total_price = @total_price.to_i + price.to_i
      end
    end
  end

  private

  def food_params
    params.permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/controllers/general_shopping_list_controller.rb
class GeneralShoppingListController < ApplicationController
  before_action :authenticate_user!
  def index
    @food_items = Food.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @public_recipes = Recipe.where(public: true)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.where(public: true).order('created_at DESC')
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!

  def new
    @recipes = Recipe.all
  end

  def create
    @recipes = Recipe.all
    @recipe_food = RecipeFood.new(recipe_food_params)

    if @recipe_food.save
      redirect_to root_path, notice: 'Recipe food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def recipe_food_params
    params.permit(:recipe_id, :food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @current_user = current_user
    @recipes = @current_user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    user = current_user
    @recipe = user.recipes.find(params[:id])
    @foods = RecipeFood.where(recipe_id: @recipe.id).includes(:food)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_url, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        flash[:error] = 'Error: recipe could not be saved'
        redirect_to new_recipe_url
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    render :edit, status: :unprocessable_entity unless @recipe.update(public: !@recipe.public)
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :description, :prepration_time, :cooking_time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/general_shopping_list_helper.rb
module GeneralShoppingListHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<div class="flex justify-center mt-48 mb-12 container mx-auto">
<div class="w-1/3 bg-white shadow-lg p-10 py-10 px-6">
<div class="flex justify-end mt-4">
<%= link_to "New Food", new_food_path, class: "py-3 px-6 bg-green-500 mb-3 text-white hover:bg-turquoise-600" %>
</div>
<h2 class="text-center text-2xl text-blue-400 mb-5">Foods</h2>
<table class="table-auto w-full">
<thead class="bg-white-400 text-black">
<tr>
<th class="py-3 text-left px-5 font-semibold">Food</th>
<th class="py-3 text-left px-5 font-semibold">Measurement unit</th>
<th class="py-3 text-left px-5 font-semibold">Unit price</th>
<th class="py-3 text-left pr-5 font-semibold" colspan="3">Action</th>
</tr>
</thread>
<tbody>
<% @foods.each do |food| %>
    <tr class="hover:bg-teal-150 border">
    <td class="right py-3 px-5"><%= food.name %></td>
    <td class="right py-3 px-5"><%= food.measurement_unit %></td>
    <td class="right py-3 px-5"><%= food.price %></td>
    <td class="right py-3 px-5"><%= food.quantity %></td>
    <td><%= button_to 'Delete', food_path(food), class: 'py-1 px-3 bg-red-500 mr-4', method: :delete %></td>
<% end %>
</tr>
</tbody>
</table>

</div>
</div>

app/views/foods/new.html.erb
<div class="flex justify-center mt-48 mb-48 container mx-auto">
  <div class="w-3/5 bg-white shadow-lg pb-10 px-10 pt-5">
      <div class="flex justify-start my-4">
         <%= link_to '<Foods', foods_path, class: 'text-teal-500' %>
         </div>
      <h1 class="text-3xl font-bold border-b-2">Add New Food</h1>
     <div>
      <%= form_with model: @food, url: foods_path, local: true do |form| %>
        <p class="mb-3 mt-5"> 
      <%= form.label :name, class: 'font-semibold pb-1' %><br />
      <%= form.text_field :name, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder: 'Food name'%>
        </p>
        <p class="mb-3"> 

      <%= form.label :measurement_unit, class: 'font-semibold pb-1'%><br/>
      <%= form.text_field :measurement_unit, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder: 'grams / units'%>
      </p>
        <p class="mb-3">
      <%= form.label :price, class: 'font-semibold pb-1' %><br />
      <%= form.number_field :price, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder: 'Price'%>
      </p>
        <p class="mb-3">
      <%= form.label :quantity, class: 'font-semibold pb-1' %><br />
      <%= form.number_field :quantity, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder: 'Quantity'%>
      </p>
      <p>
      <%= form.submit class: 'bg-orange-500 py-3 px-10 text-white hover:bg-orange-700 cursor-pointer' %>
    </p>
      <% end %>
      </div>
  </div>
</div>

app/views/foods/shopping_list.html.erb
# <% @shopping_list.each do | list | %>
#     <p> Name <%= list.name %></p>
#     <p> Measurements <%= list.measurement_unit %>
#     <p> Quantity <%= list.quantity %></p>
#     <p>Price $<%= list.price %></p>
# <% end %>
# <p>Total Price $<%= @total_price %></p>

app/views/general_shopping_list/index.html.erb
<div class="flex justify-center mt-48 mb-48 container mx-auto">
  <div class="w-4/5 bg-white shadow-lg p-10">
<h1 class="text-center text-3xl font-semibold">ShoppingList</h1>
<div class="w-1/2">
<p class="my-2"><span class="text-blue-500 font-semibold"> Amount of food items to buy: </span><span class="font-semibold text-lg"><%= @food_items.count %> </span></p>
<p><span class="text-blue-500 font-semibold">Total value of food needed: </span><span class="font-semibold text-lg"><%= @food_items.sum(:price) %></span></p>
</div>
<table  class="min-w-full table-auto border bg-white mt-5">
    <thead class="bg-white-400 text-black">
    <tr>
    <th class="py-3 text-left px-5 font-semibold">Food</th>
    <th class="py-3 text-left px-5 font-semibold">Quantity</th>
    <th class="py-3 text-left px-5 font-semibold">Price</th>
  </tr>
    </thead>
    <tbody>
        <% @food_items.each do |food_item| %>
            <tr class="hover:bg-gray-200 border">
            <<td class="right py-3 px-5"><%= food_item.name %></td>
            <td class="right py-3 px-5"><%= food_item.quantity %></td>
            <td class="right py-3 px-5"><%= food_item.price %></td>
        </tr>
        <% end %>
    </tbody>
</table>
</div>
</div>
</div>

app/views/public_recipes/index.html.erb
<div class="flex justify-center mt-48 mb-48 container mx-auto">
  <div class="w-3/5 bg-white shadow-lg p-10">
<% if @public_recipes.empty?%>
    <div>
        <p>No public recipes yet</p>
    </div>
<%else%>
<div>
<%@public_recipes.each do |public_recipe| %>
    <% sum = 0 %>
    <%= link_to recipe_path(public_recipe.id) do %>
        <div class= "shadow-lg border p-3 flex hover:bg-magenta-200 mb-6">
            
        <div class="w-1/3">
            <p class="text-xl font-semibold"><%= public_recipe.name%></p>
            </div>
        </div>
    <% end %>
<%end%>
</div>
<%end%>

app/views/recipe_foods/new.html.erb
<%= render 'recipes/recipe_foods' %>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div>
      <h2><%= pluralize(recipe.errors.count, "error") %> this recipe can not be saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  
    <%=form.text_field :name, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder: 'Recipe name' %><br />
    <%=form.text_area :description, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder: 'Recipe description' %><br />
    <%=form.time_field :prepration_time, class: 'py-2 px-4 border w-full focus:outline-cyan-400', placeholder:'Prepration time',value: "%H:%M",min: 'hh:mm:ss',max: 'hh:mm:ss'%><br />
    <%=form.time_field :cooking_time, class: 'py-2 px-4 border w-full focus:outline-orange-400', placeholder:'Cooking time',value: "%H:%M",min: 'hh:mm:ss',max: 'hh:mm:ss'%><br />
    <%= form.submit 'Create', class: 'bg-orange-500 py-3 px-6 text-white cursor-pointer hover:bg-orange-700'%>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
	<p><%=recipe.name%></p>
	<p><%=recipe.description%></p>
	<%= button_to "Remove", recipe_path(id:recipe.id), method: :delete%>	
</div>

app/views/recipes/_recipe_details.html.erb
<div class="flex flex-col items-center justify-center">
	<p class="text-3xl text-gray-700 font-semibold text-center"><%=recipe.name%></p>
	<p class="font-semibold text-gray-600 text-center">Prepration time: <%=recipe.prepration_time%></p>
	<div class="flex justify-end">
		 <%=form_with url: recipe_path, method: :put do %>
             public: <label class="switch">
               <%= check_box_tag "",@recipe.public,@recipe.public, onchange: "this.form.submit()" %>
               <span class="slider round"></span>
             </label>
             <%end%> 
    </div>
    <p class="font-semibold text-gray-600 text-center">Cooking time: <%=recipe.cooking_time%></p>
    <p class="text-center font-semibold text-xl">Description: <%=recipe.description%></p>
    <button>Generate list for your shopping</button>
    </div>

app/views/recipes/_recipe_foods.html.erb
<%= form_with model: @recipe_food, url: recipe_foods_path do |form| %>
    <% @recipes.each do |recipe| %>
        <%= form.hidden_field :recipe_id, value: recipe.id %>

        
    <% end %>
    <%= form.label :food_id, "Food" %>
    <%= form.select :food_id, Food.all.map { |food| [food.name, food.id] } %>
    <%= form.label :quantity, "Quantity" %>
    <%= form.number_field :quantity %>
    <%= form.submit "Add food" %>
<% end %>
<%= link_to "Back to recipes", recipes_path %>

app/views/recipes/edit.hmtl.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<div class="flex justify-center mt-48 mb-48 container mx-auto">
  <div class="w-4/5 bg-white shadow-lg p-10">
<h1 class="text-2xl font-bold border-b-2">Recipes</h1>

<div class="flex justify-end mt-4">
  <%= link_to "New recipe", new_recipe_path,  class: "py-3 px-6 bg-teal-500 mb-3 text-white hover:bg-orange-700" %>
  </div>
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
    <p>
      <%= link_to "Show this recipe", recipe, class: "text-green-400"%>
    </p>
  <% end %>
</div>
</div>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<%= render partial: 'recipe_details', locals: {recipe: @recipe} %>

<div>
  <%= link_to "Back to recipes", recipes_path, class: 'bg-blue-400'%>
  <%= button_to "Delete recipe", @recipe, method: :delete,class: 'bg-red-400' %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>



<h1>Users</h1>


<%= link_to "New user", users_path %>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>
  <%= button_to "Destroy this user", @user, method: :delete %>
</div>